
title: zpp & jyy
desctiption: zpp和jyy的旅程
url: https:/zppjyy.github.io
permalink: ':title/'

markdown: kramdown
#baseurl: "/karna"
full-version: "http://webjeda.com/karna-full/"

sass:
    style: compressed

  
#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

highlight: rouge

# Tracker
analytics: UA-83979019-1

include: [_pages]
version: 0.8

collections:
  loves:
    output: true
  menus:
    output: true

plugins: 
    - jekyll-paginate
    - jekyll-seo-tag
